### ISSUE TITLE
report_tex uses deprecated scrpage2.sty

### ISSUE THREAD

**Issue by glor** [sdaps/sdaps#228] opened 2020-09-27 15:25 UTC
`sdaps report_tex` uses scrpage2 which is deprecated according to this post: https://tex.stackexchange.com/questions/541766/latex-error-file-scrpage2-sty-not-found and CTAN https://ctan.org/pkg/scrpage2

**Comment by ferdisdot** [comment] 2020-09-27 17:49
Duplicate of #226

**Closed by ferdisdot** 2020-09-27 17:49 UTC

**Comment by benzea** [comment] 2020-09-29 13:10
Hrm, is it urgent to upload a new package to ctan?

**Comment by glor** [comment] 2020-09-29 13:52
Not for me. I can manually fix it with this dirty hack after report_tex fails
```
\RequirePackage{scrlfile}
\ReplacePackage{scrpage2}{scrlayer-scrpage}

```

**Comment by benzea** [comment] 2020-09-29 15:03
Yeah, report_tex isn't part of sdaps-class though, it is in the main repo and not on CTAN currently.
