### ISSUE TITLE
Convert jpg images to tif is not work

### ISSUE THREAD

**Issue by omidraha** [sdaps/sdaps#151] opened 2018-11-06 07:47 UTC
Converting scanned jpg images with `convert` command to the tif file is not work and in result pdf is not recognized any answers.

**Setup**
`
$ docker run --rm -v "$PWD":/ws/omr/  lsakalauskas/sdaps /ws/omr/sdaps setup_tex /ws/omr/example.tex
`

**Convert inputs files**

`$ docker run --rm -v "$PWD":/ws/omr/ lsakalauskas/sdaps /ws/omr/sdaps add --convert /ws/omr/1.jpg /ws/omr/2.jpg`

**Output:**
```
libdc1394 error: Failed to initialize libdc1394
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Converting input files into a single temporary file.
Processing /tmp/sdaps-convert-N1gt_Z.tif
Done
```
**Recognize**
```
$ docker run --rm -v "$PWD":/ws/omr/  lsakalauskas/sdaps /ws/omr/sdaps recognize
```
**Output:**
```
Warning: 1.tif, 0: Matrix not recognized.
Warning: 1.tif, 1: Matrix not recognized.
Warning: No page number for page 1.tif, 0 exists.
Warning: No page number for page 1.tif, 1 exists.
Warning: Got a wrong survey ID (1.tif, 0)! It is None, but should be 2829233940.
1 sheet
0.197023 seconds per sheet
```

The `example.tex` is in  [example.zip](https://github.com/sdaps/sdaps/files/2551825/example.zip).
The `1.jpg` and `2.jpg` are [here](https://user-images.githubusercontent.com/397672/48047805-8c58f780-e1ae-11e8-8585-2705e43f8c92.jpg) and [here](https://user-images.githubusercontent.com/397672/48047887-c924ee80-e1ae-11e8-9bc6-29dbb3b9e46c.jpg).
The `report_1.pdf` file is [here](https://github.com/sdaps/sdaps/files/2551947/report_1.pdf).

I also try other commands:

**1.**
` $ docker run --rm -v "$PWD":/ws/omr/  lsakalauskas/sdaps /ws/omr/sdaps  convert /ws/omr/1.jpg /ws/omr/2.jpg -o /ws/omr/output.tif`

**output**:
```
libdc1394 error: Failed to initialize libdc1394
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
```
**2.**
`$ convert 1.jpg 2.jpg -threshold 70% -monochrome out.tif`

`$ docker run --rm -v "$PWD":/ws/omr/  lsakalauskas/sdaps /ws/omr/sdaps add /ws/omr/out.tif`

**Output:**
```
Invalid input file /ws/omr/out.tif. You need to specify a (multipage) monochrome TIFF as input.
```

**3.**
I also try with pdf scanned files:

`$ docker run --rm -v "$PWD":/ws/omr/  lsakalauskas/sdaps /ws/omr/sdaps  convert /ws/omr/1.pdf /ws/omr/2.pdf -o /ws/omr/output.tif
`

The `1.pdf` and `2.pdf` are [here](https://github.com/sdaps/sdaps/files/2552140/1.pdf) and [here](https://github.com/sdaps/sdaps/files/2552144/2.pdf).

```
$ docker run --rm -v "$PWD":/ws/omr/ lsakalauskas/sdaps /ws/omr/sdaps add --convert /ws/omr/output.tif
```
**Output**

```
libdc1394 error: Failed to initialize libdc1394
Converting input files into a single temporary file.
Processing /tmp/sdaps-convert-zIapFz.tif
Done
```

```
$ docker run --rm -v "$PWD":/ws/omr/  lsakalauskas/sdaps /ws/omr/sdaps recognize
```

**Output:**

```
Warning: 3.tif, 0: Matrix not recognized.
Warning: 3.tif, 1: Matrix not recognized.
Warning: No page number for page 3.tif, 0 exists.
Warning: No page number for page 3.tif, 1 exists.
Warning: Got a wrong survey ID (3.tif, 0)! It is None, but should be 2829233940.
Warning: 4.tif, 0: Matrix not recognized.
Warning: 4.tif, 1: Matrix not recognized.
Warning: No page number for page 4.tif, 0 exists.
Warning: No page number for page 4.tif, 1 exists.
Warning: Got a wrong survey ID (4.tif, 0)! It is None, but should be 2829233940.
2 sheets
0.199866 seconds per sheet
```

**Comment by benzea** [comment] 2018-11-06 10:12
Is there a good reason for those extremely large margins?

**Comment by omidraha** [comment] 2018-11-06 11:00
There is no reason, I just print `questionnaire.pdf` to A4 papers, and then check mark answers by pen and then scan the A4 papers, and finally export them as `jpg` and `pdf` files.

I try to remove white margins with `gimp` program, but still there is no result.

New edited files: [01.jpg](https://user-images.githubusercontent.com/397672/48059971-ce466580-e1cf-11e8-9678-0833b209be86.jpg) [02.jpg](https://user-images.githubusercontent.com/397672/48059983-d9999100-e1cf-11e8-9589-f99a854738e3.jpg)
 ```

$ docker run --rm -v "$PWD":/ws/omr/ lsakalauskas/sdaps /ws/omr/sdaps add --convert /ws/omr/01.jpg /ws/omr/02.jpg
libdc1394 error: Failed to initialize libdc1394
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Syntax Warning: May not be a PDF file (continuing anyway)
Syntax Error: Couldn't find trailer dictionary
Syntax Error: Couldn't read xref table
Converting input files into a single temporary file.
Processing /tmp/sdaps-convert-ZbD3kz.tif
Done
$ docker run --rm -v "$PWD":/ws/omr/  lsakalauskas/sdaps /ws/omr/sdaps recognize
Warning: Neither 1.tif, 0 or 1.tif, 1 has a known rotation!
Warning: Neither 1.tif, 0 or 1.tif, 1 has a known page number!
Warning: No page number for page 1.tif, 0 exists.
Warning: No page number for page 1.tif, 1 exists.
Warning: Got a wrong survey ID (1.tif, 0)! It is None, but should be 2829233940.
1 sheet
0.082763 seconds per sheet
$ docker run --rm -v "$PWD":/ws/omr/  lsakalauskas/sdaps /ws/omr/sdaps report
error: XDG_RUNTIME_DIR not set in the environment
```

**Comment by benzea** [comment] 2018-11-06 11:32
No, this is actually *much* better. The corner marks are being detected (i.e. no "Matrix not recognized" error).

Now the issue is that the barcode cannot be read.

**Comment by benzea** [comment] 2018-11-06 11:35
And that is probably because you scanned at a resolution of like 133dpi or so.

**Comment by omidraha** [comment] 2018-11-06 15:13
Thanks, by changing scan options to 300dpi and white & black,  now I have result .
But the result is not exactly same as checked marks.

**Example 01**

On the `1` question,  filled check box not detected.
On the `2.2.1` question,  first crossed choice not detected.
On the `4.2` question, second filled check box detected as empty answer.

[01.jpg](https://user-images.githubusercontent.com/397672/48072766-87b63280-e1f2-11e8-9c6a-caed37de49bd.jpg)
[02.jpg](https://user-images.githubusercontent.com/397672/48072767-884ec900-e1f2-11e8-9fdb-c6a05b98fe5a.jpg)
[report_1.pdf](https://github.com/sdaps/sdaps/files/2553700/report_1.pdf)

**Example 02**

On the `2.2.3` question,  first crossed choice not detected.
On the `4.1` question,  third filled check box not detected.

[01.jpg](https://user-images.githubusercontent.com/397672/48072792-943a8b00-e1f2-11e8-92c7-d07aee632fdb.jpg)
[02.jpg](https://user-images.githubusercontent.com/397672/48072793-943a8b00-e1f2-11e8-82ad-be9ca999c453.jpg)
[report_1.pdf](https://github.com/sdaps/sdaps/files/2553702/report_1.pdf)

**Comment by benzea** [comment] 2018-11-06 15:47
If you fill it, then it is detected as a correction i.e. *not* checked (see instructions at the top of the first page). You can change this by setting `checkmode=check`.

So, example 1:
 1: filled, so detected as unchecked
 2.2.1: really think pen, considered filled, so detected as unchecked
 4.2: filled, so detected as unchecked

example 2:
 1: same …
 2.2.3: probably enough to trigger it detected as filled
 4.1: also filled …

So, everything working as expected.

**Comment by benzea** [comment] 2018-11-06 15:48
Though … "uncheck to correct" is maybe a bit weird of a string to be honest.

**Comment by benzea** [comment] 2018-11-14 13:30
Could you open a new issue/feature request to fix that? We really should have proper default instructions for all "checkmode" variations.

For now, you can do what the error message says as a workaround (i.e. change `\begin{questionnaire}` to `\begin{questionnaire}[noinfo]` to hide the instructions.

Actually, I believe that there is nothing left to do in this bug, so closing it now.

**Closed by benzea** 2018-11-14 13:30 UTC
