### ISSUE TITLE
Warnings on recognizing A6 forms

### ISSUE THREAD

**Issue by ysalmon** [sdaps/sdaps#106] opened 2017-08-10 08:19 UTC
I am generating A6 forms in order to save paper.
While sdaps is recognizing the forms, it emits warnings for each page
```
Avertissement : Neither 1.tif, 1 or DUMMY, -1 has a known rotation!             
Avertissement : Neither 1.tif, 1 or DUMMY, -1 has a known page number!
Avertissement : No page number for page 1.tif, 1 exists.
Avertissement : Got a wrong survey ID (1.tif, 1)! It is None, but should be 1275151586.
```
The forms are actually the generated PDF (blank forms) fed back to sdaps with ```--convert```.
The results seem to be read nevertheless (the forms are blank so I cannot really check but the questionnaire-id barcode is recognized and the resulting CSV has the good format).

A5 or A4 forms do not cause warnings.

Here are the input tex and an excerpt of the PDF form.
[questionnaire.tex.txt](https://github.com/sdaps/sdaps/files/1214102/questionnaire.tex.txt)
[mpe_centrale_qcmas.pdf](https://github.com/sdaps/sdaps/files/1214111/mpe_centrale_qcmas.pdf)

**Comment by benzea** [comment] 2017-08-10 09:06
Which version is that? I think this should have been fixed in 1.2.0 but maybe I missed something.

**Comment by ysalmon** [comment] 2017-08-10 15:29
It happens with the stable branch aka 1.2.0.

**Comment by benzea** [comment] 2017-08-10 16:04
Can you provide an example scan?

**Comment by ysalmon** [comment] 2017-08-10 16:20
Here is what I recognize : it is the blank PDF questionnaire converted into TIFF with the ```--convert``` option of sdaps.

![tif file with png extension so github will accept it as attachment](https://user-images.githubusercontent.com/536850/29180601-9569c8f6-7df8-11e7-97ae-2bd4be02c4ba.png)

**Comment by benzea** [comment] 2017-08-10 19:41
Oh, shit. The barcode goes over half of the page width.

**Comment by benzea** [comment] 2017-08-10 19:44
Could you switch to QR code style please? :)

Seriously, this will not work. The simple explanation is that there may be a barcode in the center (in theory) and to not mix them up only parts of the page are analysed for the barcode. Switching to QR code will make it smaller and that will keep working even with the small size of the paper.

Nothing was recognized actually. You just get an empty row in the CSV and you can see that if you start the user interface (the "invalid" page is selected")

**Comment by benzea** [comment] 2017-08-10 19:48
Btw. you can just use "sdaps . add --convert stamp_1.pdf" for testing :)

**Comment by ysalmon** [comment] 2017-08-10 20:13
Yes, this is what I do usually but I did not want to expose here the names of all my students (Goudet will not mind).

You are right, checking boxes does not lead to a change in the CSV file.

I happily switched to QR codes (they also look better !). As an alternative, I tried no_print_survey_id, but sdaps still prints it.

With QR codes enabled, recognition works (the boxes I filled with Gimp correspond to 1 in the CSV). But I got
```
Avertissement : Got different IDs on different pages for at least one sheet! Do *NOT* try to use filters with this survey! You have to run a "reorder" step for this to work properly!
```
This is very surprising since I only added 1 form consisting of 1 page. But I am fine with just ignoring it since things actually work.

**Comment by benzea** [comment] 2017-08-10 20:48
Now, that the message is printed sounds like a bug. Please just ignore it for now :)

Oh, internally there are actually two pages as there is a dummy "empty" page to handle the back side of the paper. As one might be scanning the papers in duplex mode and SDAPS needs to handle that when "--duplex" is passed to "add".

**Comment by benzea** [comment] 2017-08-20 22:54
The bogus warning was probably just caused by the same bug resulting in #107.

**Closed by benzea** 2017-08-20 22:54 UTC
